### PR TITLE
Add new IndoorEnvironmentObserved data model

### PR DESCRIPTION
**Pull request by mgaggero**
This PR introduces a data model to describe an observation of air and climate conditions and people count, for indoor use and in closed environment as rooms, classrooms, halls, laboratories.

### CODE REVIEW

**Comment by albertoabellagarcia** [comment]
This PR is missing a critical file, schema.json, that now is the source of truth and includes the specification.
See here a complete example of a well-documented schema.json
https://github.com/smart-data-models/dataModel.Energy/blob/master/ThreePhaseAcMeasurement/schema.json
to check if the schema.json is right there is an automatic tool here https://smartdatamodels.org/index.php/data-models-contribution-api/

**Comment by mgaggero** [comment]
The file schema.json is already present. I have added some description to the properties and fixed the $refs (now they point to https://smart-data-models.github.io instead of https://fiware.github.io).

**Comment by albertoabellagarcia** [comment]
It is done quite well, only one issue on two relationships. Unfortunately, and due to our documentation system, you did it correctly  we need to include the description of the relationship in the json schema. This does not allow us to put $ref but its content. so in example for refDevice it should be 
"anyOf": [
        {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[\\w\\-\\.\\{\\}\\$\\+\\*\\[\\]`|~^@!,:\\\\]+$",
          "description": "Property. Identifier format of any NGSI entity"
        },
        {
          "type": "string",
          "format": "uri",
          "description": "Property. Identifier format of any NGSI entity"
        }
      ],
     "description": "Relationship.Model:'http://schema.org/URL. Description with more than 15 chars'

The anyOf is coming from the reference you have, and the description is what you have to care. Location cannot be documented (for the moment) we'll manage it soon. so don't care.

**Comment by mgaggero** [comment]
Ok, thank you. I have replaced _refDevice_ and _refPointOfInterest_ references with their definitions and I have added the related descriptions. I left _Location_ as it is.

**Comment by albertoabellagarcia** [comment]
I've merged everything but the spec will be replaced by the official format

**Pull request merged**
